//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentImage
    {
        public int Id { get; set; }
        public string Original_Image_Path { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Content_Id { get; set; }
    
        public virtual Content Content { get; set; }
    }
}
